import React from 'react'
import {Container, Row, Col} from 'reactstrap';

import { FaUnlock } from 'react-icons/fa'
import { MdSettings } from 'react-icons/md'

export default class ZGuide extends React.Component {
  render () {
    return (
      <Container>
        <Row>
          <Col>
            <h3>1. Creating a new wallet</h3>
            <ul>
              <li>Go to <a href="https://myzenwallet.io">https://myzenwallet.io</a></li>
              <li>Enter a strong but easy to remember secret phrase. Save this somewhere and do NOT forget it.</li>
              <li>Click the <code>Generate Wallet</code> button below</li>
                <ul><li>This creates a <a href="https://en.bitcoin.it/wiki/Deterministic_wallet">deterministic wallet</a> based on your secret phrase.</li></ul>
            </ul>

            <br/>

            <h3>2. Accessing an existing wallet</h3>
            <ul>
              <li>If you've created a wallet on <a href="https://myzenwallet.io">https://myzenwallet.io</a> via the secret phrase, simply re-enter the same phrase.</li>
              <li>For those with a <code>wallet.dat</code> file generated by GUI wallets. Click <code>settings</code> (<MDSettings/>), select the <code>Load wallet.dat</code> option and load your <code>wallet.dat</code> file</li>
              <li>To unlock a single address, Click <code>settings</code> (<MDSettings/>), select the <code>Paste private key</code> option, paste in your private key and click the 'Unlock Private Key' button</li>
            </ul>
          </Col>
        </Row>
      </Container>
    )
  }
}
